# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Gradle Wrapper Validation
      # You may pin to the exact commit or the version.
      # uses: gradle/wrapper-validation-action@e2c57acffb2c9aa5a8dc6eda2bbae0b6e495bd4c
        uses: gradle/wrapper-validation-action@v1.0.3
        with:
          # Minimum expected wrapper JAR files
          min-wrapper-count: 1 # optional, default is 1
          # Allow snapshot Gradle versions
          allow-snapshots: false# optional, default is false
          
      - name: Run test
        run: ./gradlew test

      - name: Build the app
        run: ./gradlew build
      
      - name: Run test
        run: ./gradlew test
        
      - name: Run lint
        run: ./gradlew lint
